### ISSUE TITLE
hsf_get_platform returns wrong macos version number

### ISSUE THREAD

**Issue by jhmgoossens** [coin-or-tools/platform-analysis-tools#2]
Linux-ci builds of many coin-or projects also build for MacOS, but apparently the MacOS version numbers in the resulting artifacts are not correct:
- [macos-12 artifacts are called "macos106"](https://github.com/coin-or/Cbc/actions/runs/6236538144)
- [macos-13 artifacts are called "macos106"](https://github.com/coin-or/Cbc/actions/runs/7428078984)
- [macos-14 artifacts are called "macos102"](https://github.com/jhmgoossens/Cbc/actions/runs/8474119331).

Fixing these names is not critical, since we don't use Artifacts of Actions much (except for PRs), unfortunately.

Anyway, AFAIK, these names are generated by [`hsf_get_platform.py`](https://github.com/coin-or/Cbc/blob/master/.github/workflows/linux-ci.yml#L80)
This seems due to a change in [version numbering from style 10.16 to 11.01](https://stackoverflow.com/questions/65290242/pythons-platform-mac-ver-reports-incorrect-macos-version)
Looking at [examples](https://github.com/nkmk/python-snippets/blob/master/notebook/platform_usage_mac.py) of current macos "mac_ver()" output, I'd update
 ```
pf = "macos10"
version = platform.mac_ver()[0].split(".")[1]
[...]
return (pf+version).lower()

```
to
```
pf = "macos"
version = platform.mac_ver()[0].split(".")[0]
[...]
return (pf+version).lower()
```
in our fork of [hsf_get_platform.py](https://github.com/coin-or-tools/platform-analysis-tools/blob/master/hsf_get_platform.py#L46).

@tkralphs If you agree, can you make that change?

**Comment by tkralphs** [comment]
Yes, make sense.

**Comment by jhmgoossens** [comment]
Thanks for the update. 
Can you also set a new tag?
The linux-ci use this project at tag "0.0.1", so wont get the update. I'll then also update the tag ref in linux-ci.

**Comment by tkralphs** [comment]
Pushed tag 0.0.2.

**Comment by jhmgoossens** [comment]
Thanks, [it works](https://github.com/jhmgoossens/Cbc/actions/runs/8483084884)!
Cbc-arm64-macos14-gcc1320.tar.gz
Cbc-x86_64-macos13-clang150.tar.gz
Cbc-x86_64-macos13-gcc1320.tar.gz

I’ll include this change in the CI changes.
